### ISSUE TITLE
Need help

### ISSUE THREAD

**Issue by groupebestogo** [icedevml/ntag424-backend#26]
Hello
First of all thanks for this server. It's almost impossible to find something like this open source.
I would like to use NFC tags with backend server to verify tags are genuine.
I'm using ntag424 and would like to use the encrypted SUN messaging to add additional information like group the tag belongs to.
How do I add tags to your server?
How can I customize the confirmation page with own design.
Is it possible to setup in a way to have online and offline validation with automatic database sync when got internet is available?
Can I make it multiple languages?

Thanks for your time

**Comment by icedevml** [comment]
Hello,

> I would like to use NFC tags with backend server to verify tags are genuine.

I think this repository would be perfectly fine for this purpose.

> I'm using ntag424 and would like to use the encrypted SUN messaging to add additional information like group the tag belongs to.

If you want to encode this on the tag, I think the proper place to add this information is in so-called "file data" part of the URL (`EncFileData`).

> How do I add tags to your server?

It's not needed to add them manually to this server, you need to encode SDM on the tag.

> Is it possible to setup in a way to have online and offline validation with automatic database sync when got internet is available?

If a dedicated Android application would be written for that, I think yes, without huge problem there could be an offline validation as well (i.e. you scan and then the application waits with the verification until Internet connection is available).

> Can I make it multiple languages?

Yes, with some modifications of the web application.

**Comment by groupebestogo** [comment]
Thanks for all
