### ISSUE TITLE
Can't get NTAG 424 tag to work with the sample backend - programmed with TagXplorer 

### ISSUE THREAD

**Issue by piejanssens** [icedevml/ntag424-backend#31]
These are the steps I took [based on the instructions from an NXP TechSupport](https://community.nxp.com/t5/NFC/Configuring-NTAG-424-DNA-with-Encrypted-Part-and-CMAC-Part/m-p/1049316/highlight/true#M7082):

1. Select tab "Mirroring features", subtab "NTAG 424 DNA Tag Tamper"
2. Select protocol `https://´
3. Paste target URL: `sdm.nfcdeveloper.com/tag?cmac=0000000000000000&picc_data=000000000000000000000000000000`
4. Determine offsets by setting cursor behind `cmac=` (37) and behind `picc_data=` (64) and write them down
5. Click "Write to tag"
7. Select tab "NTAG 424 DNA Tag Tamper"
8. Select "Security Management"
9. Click "Authenticate First" (using default zero-key)
10. Click "Get / Change File Settings"
11. Change communication type to "Enciphered"
12. Select SDM options: "SDM and Mirroring" / "SDM Read Counter" / "UID (for mirroring)"
13. Set Meta Read Access Key: 01
14. Set File Read Access Key: 02
15. SDM Counter Ret Access Key: 0F (not sure what this value represents though)
16. Set SDM MAC Input Offset: 37
17. Set SDM Mac Offset: 37
18. Set PICC Data Offset: 64
19. Click "Change File Settings"

This is an example of a resulting URL after scanning the tag, which fails the signature validation.
`https://sdm.nfcdeveloper.com/tag?cmac=3024237ECA5E5B44&picc_data=D3754B026C37ADE1E02BF49CF491F4`

**Comment by piejanssens** [comment]
I'm trying to understand the default offsets that are set when I program the tag with the NFCDeveloperApp, but I can't figure it out 😄 

This is the URL returned from the NDEF:
`https://sdm.nfcdeveloper.com/tag?_____TRIAL_VERSION______NOT_FOR_PRODUCTION_____&picc_data=4AA4FB317006013DDA6F995F13E15ECC&enc=40D7C3DA6F86B07494B2707F50279423&cmac=135AFB956B4603A3`

These are the offsets programmed by NFCDeveloperApp:
![image](https://user-images.githubusercontent.com/829098/163119680-72b3ee46-1a11-49fd-aa05-6c762c5726cb.png)

This is what I would expect them to be looking at the indexes of the different URI parameters:

picc_data: 90
![image](https://user-images.githubusercontent.com/829098/163120047-225f155a-c987-46e8-bfe1-bc9b7ecdc127.png)

enc: 127
![image](https://user-images.githubusercontent.com/829098/163120178-2a17d3f2-7c71-41d4-abd4-b73244a8cbf9.png)

cmac: 165
![image](https://user-images.githubusercontent.com/829098/163120341-5f4ac064-e5b0-492b-9ce1-a54d92f5f6d1.png)

**Comment by piejanssens** [comment]
This works fine. I belief I was not using the correct keys.

**Comment by rizalsofyans** [comment]
Hello @piejanssens , what is the link that you entered the first time in TagXplorer? Is it like this `https://sdm.nfcdeveloper.com/tag?picc_data=00000000000000000000000000000000&enc=00000000000000000000000000000000&cmac=0000000000000000?`

![image](https://github.com/icedevml/sdm-backend/assets/82468736/34dab2f4-ad12-4e38-b8d5-720a32aa05be)

**Comment by jTanG0506** [comment]
Any tips on how to get this working with the `file_data` like in this example, via TagXplorer?
https://sdm.nfcdeveloper.com/tag?picc_data=FD91EC264309878BE6345CBE53BADF40&enc=CEE9A53E3E463EF1F459635736738962&cmac=ECC1E7F6C6C73BF6
