### ISSUE TITLE
Dynamic URL validation - previous URLs are still valid

### ISSUE THREAD

**Issue by lukagrbec** [icedevml/ntag424-backend#33]
Hello,
firstly, thanks for creating this library. I've been testing it and have noticed, that when scanning a tag, the counter does increase, but the URL from the previous scan (counter - 1) is still valid. Is this right behaviour? Or should the previous URL be invalid, so someone couldn't save the URL and display the tag is valid?

Thanks for your time.

**Comment by icedevml** [comment]
Hello @lukagrbec,

the sdm-backend doesn't have any mean of database, so it's unable to track the counter values associated with the UIDs.

At the moment, you can add this feature manually to integrate with the database of your preference.

We will consider adding this as an optional feature in the future versions.

**Comment by lukagrbec** [comment]
Thank you for the explanation and suggestion.
