### ISSUE TITLE
CAN NOT VALIDATE NON ZERO KEY SIGNED MESSAGES

### ISSUE THREAD

**Issue by bhavin-qryptal** [icedevml/ntag424-backend#39]
The latest version of the SDM backend is unable to validate tags created with non zero keys and NFC Developer App. I was able to get validation working by rolling back code to Sep 2022 commit. So it is suggesting that the issue was introduced in commits after Sep 2022.

**Comment by icedevml** [comment]
Hello,

thanks for your issue and sorry for late reply. We are working on synchronizing the demo app with the recent sdm-backend open source version. For now, the workaround is as you've previously suggested - reverting back to the code from Sep 2022 commit.
