### ISSUE TITLE
Wrong key used for PICC and CMAC

### ISSUE THREAD

**Issue by p-gentili** [icedevml/ntag424-backend#5]
Hi,
I don't know if this is an error on your side or in the documentation I have but it seems that, according to the documentation:

- for PICC decryption the SDMMetaReadKey is needed
- for CMAC the SDMFileReadKey is needed.

In your implementation you use them in the opposite way instead.

Please let me know what you think about this.
Thanks

**Comment by icedevml** [comment]
Hello, thanks for your suggestion. I will review the datasheet to ensure the naming is correct and get back to you soon.

**Comment by icedevml** [comment]
@p-gentili Could you look at this patch? Does it address the problem properly?

https://github.com/icedevml/ntag424-backend/pull/6

**Comment by icedevml** [comment]
@p-gentili Thanks.
