### ISSUE TITLE
Instructions on how to set custom keys on the chip

### ISSUE THREAD

**Issue by softzer0** [icedevml/ntag424-backend#7]
I see in config file default keys (all zeros) are being used, but how to change them when configuring the NTAG 424 DNA chip (through TagWriter/TagXplorer interface)? Any instructions for that? Thanks in advance, man!

**Comment by icedevml** [comment]
Hello,

using TagWriter I think it's not possible (software not capable of changing keys), but using TagXplorer it should work fine through this interface (look at the right side, first you need to authenticate with zero key and then you can go to `Change Keys`). Unfortunately I haven't used TagXplorer yet, so I can only instruct you "theoretically".

![image](https://user-images.githubusercontent.com/6976513/89458477-6091e980-d767-11ea-8a1c-28eb008d4a9b.png)

In my setup, I use my custom Android application (implemented according to the datasheet and application notes) that performs key changing.

**Comment by softzer0** [comment]
Wow, that was fast, thank you for the answer! So I just go there and select "AES Auth", "Application Auth" and click on "Authenticate First", then I go to "Change Key" section and input there some random key and save. I'll try it once I get my hands on those tags and report you back.

**Comment by icedevml** [comment]
Sure. If you would report back whether it worked or not then it would be very helpful :)

**Comment by softzer0** [comment]
@icedevml I have one question not much related to this, so sorry for digression. I was wondering, how do you calculate the offsets if the app doesn't do that for you? In the instructions you provided for TagWriter it's indicated that the offset number is found automatically when you set a pointer in the URL, but I don't see that being the case in TagXplorer (you have to manually input the number). How should I do this?

**Comment by softzer0** [comment]
One question - do I have to set custom keys after I've configured URL or before, or that doesn't matter?

**Comment by softzer0** [comment]
Before I do this, I need to clear out two things:
* When I need to change those default SDM keys - before, or after configuring an URL?
* After I set new keys, do I need to change anything in the picture below related to SDM keys?
![image](https://user-images.githubusercontent.com/7763533/89530031-1738ad00-d7ee-11ea-84b8-435c7ec40794.png)

**Comment by icedevml** [comment]
Settings marked 16-21 are responsible for configuring the scheme of SDM. I.e. the SDM URL might have many different formats, e.g.:

```
http://myserver.example/tag?picc_data=EF963FF7828658A599F3041510671E88&cmac=94EED9EE65337086
```
or
```
http://myserver.example/tag?picc_data=FD91EC264309878BE6345CBE53BADF40&enc=CEE9A53E3E463EF1F459635736738962&cmac=ECC1E7F6C6C73BF6
```
or many different options. These checkboxes determine the particular format you will be using, more details are available in the NTAG 424 DNA datasheet.

Settings marked with 17-19 are numbers of keys used for particular features, namely:
* 17 - key used to compute CMAC (the digital signature)
* 18 - key used to encrypt EncFileData (if present)
* 19 - key used to read the value of the counter

depending on the URL format chosen (settings 16-21), some keys are meaningless or have altered functions, again you need to consult datasheet.

I think it's the best to first change the encryption keys and then perform any additional configuration, but that's up to the user.

**Comment by softzer0** [comment]
Okay, thank you for the answer again! Since I'm a total newbie on this matter I'll take one-two chips and play with configuring if I fail to set it up properly from the start. If I succeed I'll notify you here, or if I get stuck, I will bore you again. 😃

**Comment by Blackcode** [comment]
Hello icedevml,
i do not manage either to generate a working URL with TagXplorer. 
Can you post what settings you are using to write your tags?

Thanks

**Comment by softzer0** [comment]
Tested it finally and I can confirm that this method of key changing works! Thank you once again @icedevml for the help!

**Comment by icedevml** [comment]
You're welcome, thanks for confirming!
